# Generated by Django 4.2.4 on 2023-09-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('residential_address', models.CharField(max_length=100)),
                ('student_identity_number', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
