# Generated by Django 4.2.4 on 2023-09-14 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_user_country_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_number',
            field=models.CharField(default=uuid.uuid4, max_length=16, unique=True),
        ),
    ]
