# Generated by Django 4.2.4 on 2023-09-14 05:48

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_user_user_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_number',
            field=models.CharField(default=registration.models.User.generate_user_number, max_length=16, unique=True),
        ),
    ]
